### ISSUE TITLE
Can't Stark Jack Server, Getting Error TypeError: Argument 0 is not Java class: [JavaPackage org.simpleframework.http.core.Container]

### ISSUE THREAD

**Issue by pnewhook** [tlrobinson/narwhal#77]
I'm running the 280 North fork on Windows XP
When I try to run the jack samples I get the following 

```
Loading configuration module at C:\Gited\bar\jackconfig.js
TypeError: Argument 0 is not Java class: [JavaPackage org.simpleframework.http.core.Container].
org.mozilla.javascript.EcmaError: TypeError: Argument 0 is not Java class: [JavaPackage org.simpleframework.http.core.Container].
C:\Gited\narwhal\packages\jack\lib\jack\handler\simple.js#13)
    at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3659)
    at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3637)
    at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:3665)
    at org.mozilla.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:3684)
    at org.mozilla.javascript.JavaAdapter.js_createAdapter(JavaAdapter.java:173)
    at org.mozilla.javascript.JavaAdapter.execIdCall(JavaAdapter.java:126)
    at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:129)
    at org.mozilla.javascript.BaseFunction.construct(BaseFunction.java:338)
    at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1735)
    at script(C:\Gited\narwhal\packages\jack\lib\jack\handler\simple.js:13)
    at script.main(C:\Gited\narwhal\packages\jack\lib\jackup.js:131)
    at script(\C:\Gited\narwhal\packages\jack\bin\jackup:2)
    at script(C:\Gited\narwhal\bin\../lib/sandbox.js:251)
    at script(narwhal.js:205)
    at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:845)
    at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:164)
    at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
    ato rg.mozilla.javascript.gen.C__Gited_narwhal_engines_rhino_bin____bootstrap_js_1._c_anonymous_1(Unknown Source)
    at org.mozilla.javascript.gen.C__Gited_narwhal_engines_rhino_bin____bootstrap_js_1.call(Unknown Source)
    at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:76)
    at org.mozilla.javascript.gen.C__Gited_narwhal_engines_rhino_bin____bootstrap_js_1._c_script_0(Unknown Source)
    at org.mozilla.javascript.gen.C__Gited_narwhal_engines_rhino_bin____bootstrap_js_1.call(Unknown Source)
    at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:405)
    at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3066)
    at org.mozilla.javascript.gen.C__Gited_narwhal_engines_rhino_bin____bootstrap_js_1.call(Unknown Source)
    at org.mozilla.javascript.gen.C__Gited_narwhal_engines_rhino_bin____bootstrap_js_1.exec(Unknown Source)
    at org.mozilla.javascript.tools.shell.Main.evaluateScript(Main.java:563)
    at org.mozilla.javascript.tools.shell.Main.processFileSecure(Main.java:485)
    at org.mozilla.javascript.tools.shell.Main.processFile(Main.java:451)
    at org.mozilla.javascript.tools.shell.Main.processSource(Main.java:443)
    at org.mozilla.javascript.tools.shell.Main.processFiles(Main.java:196)
    at org.mozilla.javascript.tools.shell.Main$IProxy.run(Main.java:117)
    at org.mozilla.javascript.Context.call(Context.java:517)
    at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:514)
    at org.mozilla.javascript.tools.shell.Main.exec(Main.java:179)
    at org.mozilla.javascript.tools.shell.Main.main(Main.java:157)
```

In the past I was able to fix this by setting my NARWHAL_CLASSPATH to C:\Gited\narwhal\packages\jack\jars\simple-4.1.10.jar but it no longer works.

**Comment by kriszyp** [comment]
Here is the fix:
http://github.com/kriszyp/narwhal/commit/750eb21361f1299cabb63a5c3f592dbb06f8557b
